### PR TITLE
fix: update generator prompt message

### PR DESCRIPTION
**Pull request by gtsiolis**
Minor update in the generator prompt message.

This will add a `?` at the end of the last question (_What's the repo of your project_) to follow the pattern used in all the rest of the prompt messages during project generation.

### CODE REVIEW

**Comment by gtsiolis** [comment]
@ulivz WDYT?

**Comment by bencodezen** [comment]
@gtsiolis Sorry I think I messed up the merge conflict. Can you make sure I did everything correctly?

**Comment by gtsiolis** [comment]
No worries @bencodezen! Thanks for taking a look. It should be good now. 🏀

**Review by bencodezen — APPROVED** [review]
Looks great. Thanks @gtsiolis!

**Pull request merged**
